#
# Reference the base spark image
FROM mesosphere/spark:2.3.1-2.2.1-2-hadoop-2.6
ENV CLASSPATH=/opt/spark/dist/jars/spark-streaming-kafka-0-10_2.11-2.2.0.jar
# Install the pip3 utility so we can install the Python package
RUN apt-get update && apt-get install -y software-properties-common
RUN add-apt-repository universe
#RUN apt-get install -y gcc python-devel libev libev-devel
RUN apt-get install -y python-pip python-pandas build-essential python-dev python3-pip
RUN pip3 install xmltodict py4j kafka-python cassandra-driver beautifulsoup4 lxml




